### ISSUE TITLE
https://killr.io freeze

### ISSUE THREAD

**Issue by Ashtor** [whackashoe/killr-cmdline#1]
I just tried to enter a md5 hash which is encoded from a 3-lined text and as soon as I save it and then open the link with that md5 hash,it freeze and it takes a long time before anything can be done . Fix the issue

**Comment by whackashoe** [comment]
erm.. whats the link?

**Comment by whackashoe** [comment]
nvm im able to reprod here w. quick test

**Comment by Ashtor** [comment]
I just made one just for you to test: here is the link I made on killr: https://killr.io/gvlas

**Comment by whackashoe** [comment]
can you try now, either clear you cache or go to "https://killr.io/build/scripts.min.js" and refresh at least once on there to make sure then try - believe the issue is fixed well at least on my end it is.

**Comment by Ashtor** [comment]
I just cleared the caches and now tried a new one again and it seems that the issue got fixed.. What was the cause of the issue? and if it happens again.. Should I just visit https://killr.io/build/scripts.min.js and then clear caches? or I dont need to do it anymore?

**Comment by whackashoe** [comment]
cool! there is a language parser which attempts to detect how to render the text. this was going berzerk attempting to parse the hash, idk why.. but ive had same issue before with overly long strings, i think the randomness of it is a bit hard on her. anyways, just updated highlight.js and the newer version fixes this issue.

**Comment by whackashoe** [comment]
thanks for letting me know, though in future might wanna keep in mind that "Fix the issue" is a bit rude. cheers :+1:
